### ISSUE TITLE
Re-introduce stage & cluster fields to graphcool.yml file

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#1461]
Based on a lot of feedback about the 1.0 beta preview, we're changing a couple of things to make the deployment configuration **more explicit** and therefore more transparent. We've also received the feedback that "magic env vars" (concretely `GRAPHCOOL_SECRET` & `GRAPHCOOL_STAGE`) are rather confusing than convenient, another reason to make these configuration options explicit.

Here are the changes:

- Add `stage` field to `graphcool.yml`
- Add `cluster` field to `graphcool.yml`
- Remove support for `GRAPHCOOL_SECRET`, `GRAPHCOOL_STAGE` and `GRAPHCOOL_DISABLE_AUTH` environment variable
- Remove `--stage` / `-s` flag from all commands
- Rename `--dotenv` to `--env-file` / `-e`
- Remove `~/.graphcool/cache.yml` and rename `~/.graphcool/config.yml` to `~/.graphcoolrc` again
- ? Remove interactive deploy mode

## Example `graphcool.yml`

```yml
service: example-airbnb
stage: dev
cluster: local
secret: ${env:GRAPHCOOL_SECRET}

datamodel:
- database/datamodel/types.graphql
- database/datamodel/enums.graphql
```

Note that clusters can also point to clusters hosted with Graphcool Cloud. Example:

```yml
cluster: my-workspace/prod-eu-west-1
```

## Benefits

- More transparent and explicit, therefore easier to get started with
- Still very flexible since every configuration option (`secret`, `stage`, `cluster`, ...) can be set via environment variable and therefore easily be scripted (e.g. for CI environments)
- Simplifies tooling that reads data from `graphcool.yml` (e.g. GraphQL Playground which reads this information via the graphql-config extension for graphcool)

**Comment by kbrandwijk** [comment]
There's a couple of things I don't really get, again I would like to draw the parallel to Serverless.
> Remove interactive deploy mode
Why would that need to be removed?
And why support only a single stage/cluster for deployment?

**Comment by marktani** [comment]
When `stage` is missing from `graphcool.yml`, this is returned in the latest alpha:

```sh
 ▸    Invalid graphcool.yml file
 ▸    graphcool.yml should have required property 'stage'. missingProperty: stage
```

I think we should ask for a stage name instead and add it to `graphcool.yml` in an interactive manner.

@schickling @timsuchanek wdyt?

**Comment by marktani** [comment]
@kbrandwijk the idea is that the stage and cluster can be handled by `.env` files, which is more explicit. I agree that this is not mutually exclusive to an interactive mode, but at least this anwers your second question 🙂

**Comment by stephenhandley** [comment]
Sorry, reading this I'm left scratching my head. Is the stage I'm specifying in graphcool.yml a default? However, there's no stage specifiable via the CLI? That seems to imply that there would need to be multiple graphcool files (one for each stage), which is something that seems counterproductive. I agree with @kbrandwijk the approach serverless takes works well enough and is worth looking at for reference:
https://serverless.com/framework/docs/providers/aws/guide/variables/#current-variable-sources

In my case I'm doing something the following
```
provider:
  name: aws
  region: us-west-1
  runtime: nodejs6.10
  stage: dev
  memorySize: 512
  timeout: 5
  environment: ${file(./env/${opt:stage, self:provider.stage}.yml)}
```

This specifies default stage of "dev" but can override that by passing `--stage` to the CLI. I then have environment specific vars in the associated yml files and appropriately gitignored. 

That works for serverless, but I'd like to be able to use the same env-specific configuration files across both graphcool and serverless.

It sounds like dotenv is supported, so I suppose my best guess is to rework my serverless config so that it uses dotenv (i.e. a simplified version of this https://forum.serverless.com/t/how-to-deal-with-environment-variables-source-control-serverless-yml/2248/2) 

But then I'm still left wondering what purpose the "stage" field in my graphcool.yml is serving and as such, why it is required. 

would love to see a graphcool example project supporting multiple environments.

**Comment by stephenhandley** [comment]
I'm unable to get .env files working, even without the cli switch. When I create a new graphcool project via graphcool-framework/0.11.5 and add the twilio template and then create a .env file with the following

TWILIO_ACCOUNT_SID=BLAH
TWILIO_AUTH_TOKEN=BLOOP
and then run graphcool deploy i see the following format of errors for TWILIO_ACCOUNT_SID and TWILIO_AUTH_TOKEN

/graphcool.yml: A valid environment variable to satisfy the declaration
 ▸    'env:TWILIO_ACCOUNT_SID' could not be found.
I've tried using -e and --env-file also with no luck there either.

**Comment by marktani** [comment]
Hey Stephen, as I said in the other issue, this repository is about Prisma 🙂 
The original post was using old terminology, I updated that to prevent further confusion.

Please report back [in this repository](https://github.com/graphcool/graphcool-framework/) with questions about Graphcool Framework. Thanks!

Here's a [comparison between Graphcool Framework and Prisma](https://www.graph.cool/forum/t/graphcool-framework-and-prisma/2237?u=nilan).

**Comment by stephenhandley** [comment]
@marktani I'm commenting here because you linked this issue as the solution to the issue I originally found in the framework repository
https://github.com/graphcool/graphcool-framework/issues/271#issuecomment-359773683

I'm clear on the difference between prisma and graphcool framework, but the communication and documentation process since the roll out has been pretty abysmal on your guys' end. If you'd prefer I delete and move my comments to that issue, I'm fine with doing so, but you'll probably want to update your comment and not link to this issue as the solution.

**Comment by marktani** [comment]
Thanks for this clarification, mea culpa 🙌 
I removed my comment from the issue you are referring to, you don't have to remove any comments 🙂 

I'd love to hear your thoughts on how we can improve our communication and documentation process, feel free to shoot me a message to `nilan@graph.cool` or in Slack.

Thanks for your feedback Stephen!
