### ISSUE TITLE
Can't set default value when my scalar type is an enum

### ISSUE THREAD

**Issue by marceloogeda** [graphcool/graphcool#575]
**What is the current behavior?**

After I choose an enum type that I have created for my field.
When I try to set a default value the field frozen and I can't fill it with any value.

<img width="617" alt="screen shot 2017-09-20 at 19 01 50" src="https://user-images.githubusercontent.com/3205036/30669864-5783b5c0-9e36-11e7-9574-5e320b67fdc1.png">

<img width="615" alt="screen shot 2017-09-20 at 18 54 34" src="https://user-images.githubusercontent.com/3205036/30669868-5cdd6304-9e36-11e7-8b5e-3e7e9e182f16.png">

**What is the expected behavior?**

I should choose a value from my enum values as a default value to the field.

**Comment by iamclaytonray** [comment]
Workaround, for now: Create the type and whatnot, ignore the default value, save it. Open that type back up and update the default value, and it will work. I know it's not a good solution but it works for me until there is an actual bug fix

**Comment by iamclaytonray** [comment]
I'm no expert and haven't seen the source code but I'm guessing it does that because the default value is set to `null`. 

@marktani - If you conditionally set the default value based on the current state of the selected data  type under that field, I think that would resolve this issue. For example, say I have a Post type that has `title: String!`. If the type is string, set the default value to `""`. For Enums, I would imagine it would be `{}`. And so on, and so forth. I could be completely wrong. I've only been in React for like 6 months, so still totally new. Thoughts?

**Comment by marktani** [comment]
Thanks @iamclaytonray for chiming in, I think that's a great idea!

Let's keep further discussion about this here: https://github.com/graphcool/console/issues/1220

Closing this as duplicate.
