### ISSUE TITLE
Project download for ejected projects should be put into src folder

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool#602]
Currently, downloading a legacy project uses `code` folder. Should be renamed to `src`.

**Comment by do4gr** [comment]
Currently when ejecting a project we create a folder structure to store files with code/schema/query for functions and permissions.
For this we have `./code` for files belonging to functions and `./query` for permission queries. This feels a little weird since the code folder then also contains queries and schemata for functions and not all queries are in the query folder as expected.

The yml file will then look inconsistent.
For subscription functions it can for example contain:
* `code: ./code/CreateCustomer.js`
* `query: ./code/CreateCustomer.graphql`

And for permission queries: 
* `query: ./query/CreateCustomer.graphql`

**Comment by timsuchanek** [comment]
My understanding is that we want to put everything into `./src`, the queries and js files.
This approach is the least opinionated and most consistent.
My proposal is to put permission queries into `./permissions` to separate these clearly.

**Comment by schickling** [comment]
* Permission queries should be exported all into one file under `src/permissions.graphql` and be referenced via GraphQL operation names
* The `code` and `query` folder should be unified into a `src` folder

**Comment by marktani** [comment]
> Permission queries should be exported all into one file under src/permissions.graphql and be referenced via GraphQL operation names

is that possible already, @timsuchanek? how does the syntax for this look like?

**Comment by kbrandwijk** [comment]
> Permission queries should be exported all into one file under src/permissions.graphql and be referenced via GraphQL operation names

Why would you want to combine all of those queries in a single file? I have seen quite a few people create a folder structure per Type. Separate files for each query makes that a lot easier.

**Comment by schickling** [comment]
Good point, in that case I'd suggest one merged file per type. Here is an example:

```
.
└── src
    ├── hello.js
    └── permissions
        ├── Post.graphql
        └── User.graphql
```

**Comment by timsuchanek** [comment]
How do we want to refer to the operations?
I suggest using `:` like [serverless does](https://serverless.com/framework/docs/providers/aws/guide/variables/):
```yaml
permissions:
- operation: User.create
  query: ./src/permissions/Post.graphql:create
```

**Comment by kbrandwijk** [comment]
Except that it's not a variable. For functions, serverless uses the dot syntax: `handler: foo.bar` indicates the `bar` method in `foo.js`. So query: `Post.create` would look for `query create {...}` in Post.graphql.

**Comment by marktani** [comment]
@timsuchanek I assume in your proposal, the `Post.graphql` file would look somewhat like this:

```graphql
query create {
  SomeUserExists
}

query delete {
  SomeUserExists
}
```

this now conflicts with the topic covered here #703. I suggest to abstain from merging multiple permission queries into one file for now, for exactly this reason.

My suggestion for a short-term change is this:

```sh
.
└── src
    ├── hello.js
    └── permissions
        ├── create.graphql
        └── delete.graphql
```

which would fulfill the original request of streamlining the `code` vs. `src` terminology.

Being able to refer to a specific query in one file is unfortunately a bigger task, as I sketched out above and should be tackled at a later point in time.

**Comment by do4gr** [comment]
I'll try to propose a solution that covers this issue and at the same time allows us to move forward with https://github.com/graphcool/graphcool/issues/456 and https://github.com/graphcool/graphcool/issues/703

**Comment by marktani** [comment]
lists should be intended:

```yml
permissions:
  - operation: Post.update
    query: ./src/permissions/Post.graphql:adminUpdatePermission
  - operation: Post.delete
    query: ./src/permissions/Post.graphql:adminDeletePermission
```

**Comment by lastmjs** [comment]
I just want to voice that I think the old console format of permissions without the query header definitely needs to go, since it isn't valid query syntax and may lead to confusion because of that.

**Comment by lastmjs** [comment]
Also, can we discuss how `fields` will play into all of this? I sometimes have multiple distinct permission queries that should apply for a certain operation, based on the `fields`. What I'm doing right now is creating a separate file for each operation based on the `fields`. It's kind of awkward though, because I end up with file names like the following:

```
--permission-queries
----course
------course-read-all.graphql
------course-read-title-price.graphql
```

What happens when my permission requirements change and I need to add more specificity based on `fields`? I will have to go and change potentially multiple file names. It's going to get messy.

I want to bring this up to see if there is a more elegant solution that can be built in.

**Comment by kbrandwijk** [comment]
:confused:

**Comment by marktani** [comment]
This is now implemented 🙂 @do4gr will share more details soon.

**Comment by do4gr** [comment]
We implemented the folder changes in line with https://github.com/graphcool/graphcool/issues/602#issuecomment-333561263 

The new permissions format can also already be used. It is not required yet though. Known limitations of the new format are tracked here: https://github.com/graphcool/graphcool/issues/772

**Comment by do4gr** [comment]
@lastmjs 
With the new possibility of addressing queries within one file by name you could bundle your queries in one file per type/relation and would reference them by query name. This way you are working within one file when changing around permissions on a field level and do not need to change filenames.

```graphql
query courseReadAll { SomeUserExists {...}}

query courseReadTitlePrice { SomeUserExists{...}}
```


```
.
└── src
    ├── SampleFunction.js
    ├── SampleFunction.graphql
    └── permissions
        └── Course.graphql
```
