### ISSUE TITLE
Permission queries are not correctly stored

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool#703]
**What is the current behavior?**

Storing a permission query does not work correctly.

---

Storing the following permission query:

```graphql
query permission($user_id: ID!) {
  SomeUserExists(
    filter: {
      id: $user_id
      role: ADMIN
    }
  )
}
```

does not work. when running the according operation, you get this error message:

![pasted image at 2017_09_30 12_48 am](https://user-images.githubusercontent.com/1780597/31038880-758ff49e-a579-11e7-9d0b-bd6c12a4c427.png)

As you can see, the string 

```
query ($user_id: ID)
```

is prepended to the permission query supplied in the permission file.

**What is the expected behavior?**

The permission query is correctly stored, without being adjusted before.

**Comment by do4gr** [comment]
The storing is not the problem here. For the above sample query the console would be sending us 
```
{
  SomeUserExists(
    filter: {
      id: $user_id
      role: ADMIN
    }
  )
}
```
Which is what we store and use to validate the query when necessary. During the validation step we automatically generate and prepend `query ($user_id: ID)` to make the query valid.

When the user now has the complete query in his permission file and has the CLI send 
```
query permission($user_id: ID!) {
  SomeUserExists(
    filter: {
      id: $user_id
      role: ADMIN
    }
  )
}
``` 
we still prepend `query ($user_id: ID)` which results in the invalid query error.

Sending the same format as the Console works if send through the CLI.

Our proposal is to document the expected format for permission queries (without the `query` keyword and the variables definition) and add validations for that format when creating or updating permission queries. This saves the user the need to write boilerplate  that we already know how to infer.

**Comment by marktani** [comment]
That's a great suggestion. Then the careful documentation and validation is really crucial. 

I'm closing this, in favor of #655 and #456.

**Comment by do4gr** [comment]
See https://github.com/graphcool/graphcool/issues/602

**Comment by lastmjs** [comment]
Where is the discussion for this happening? None of the referenced issues seem to be actively discussing this, and I have some feedback

**Comment by kbrandwijk** [comment]
https://github.com/graphcool/graphcool/issues/602#issuecomment-333561263 is the latest I believe.
