### ISSUE TITLE
Console: service definition of an upgraded service is not correct

### ISSUE THREAD

**Issue by freder** [graphcool/graphcool#873]
**What is the current behavior?**

- upgraded the  project
- downloaded the project definition 
- did `npm install -g graphcool@next` (`graphcool version` shows `graphcool/0.7.0 (darwin-x64) node-v8.7.0`)
- ran `graphcool info`

shows this:
![screen shot 2017-10-17 at 15 41 05](https://user-images.githubusercontent.com/724844/31668508-b12224aa-b352-11e7-9692-f71c6afc6521.png)

**Comment by marktani** [comment]
Thanks a lot for reporting this @freder!
The reason is a recent change in the format for `.graphcoolrc`.

This is the format currently used in the downloaded zip folder:

```
default: prod
environments:
  prod: <some-id>
```

This is the new expected format:

```
targets:
  prod: shared-eu-west-1/<some-id>
  default: prod
```

here is what you need to use instead of `shared-eu-west-1` depending on the region of your project:

![image](https://user-images.githubusercontent.com/1780597/31669028-2561ed72-b354-11e7-9542-ddcff7ff971a.png)

So, until the format has been adjusted for the downloaded zip, you can manually adjust it 🙂

**Comment by marktani** [comment]
Also, a `README.md` file with instructions should be included in the zip file.

**Comment by timsuchanek** [comment]
This is done and currently deploying to the production Console.
I added a README and the .graphcoolrc now contains the latest format.
